# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.cache/wt [current_project]
set_property parent.project_path D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/fft_freq_meter.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/ad7606_driver.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/seg_driver.v
  D:/FPGA/数电作业存档/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/adc_to_fft_buffer.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/fft_configor.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/freq_to_uart.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/freq_screen_driver.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/auto_nrst.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/new/digital_agc.v
  D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
}
add_files D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/constrs_1/new/test_clk.xdc
set_property used_in_implementation false [get_files D:/FPGA/audio_analyze_7a35t/audio_analyze_7a35t.srcs/constrs_1/new/test_clk.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
